# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
        args: ['--allow-missing-credentials']
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
        # args: ["--config=.gitleaks.toml"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          # - '--args=--config=__GIT_WORKING_DIR__/.tflint.hcl'
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
      # - id: terraform_checkov
      #   args:
      #     - --args=--quiet
      #     - --args=--compact
      #     - --args=--skip-check CKV2_AZURE_1 #  "Ensure storage for critical data are encrypted with Customer Managed Key"
      #     - --args=--skip-check CKV_AZURE_206 #  "Ensure that Storage Accounts use replication"
      - id: terraform_trivy
        args:
          - --args=--config=__GIT_WORKING_DIR__/trivy.yaml
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
          - --args=--format=table
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.19.0"
    hooks:
      - id: terraform-docs-system
        args: ["markdown", "table", "--output-file", "README.md", "./"]
